version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  php:
    image: php:8.1-fpm
    volumes:
      - ./seu_projeto:/var/www/html
    command: ["php", "artisan", "serve", "--host", "0.0.0.0", "--port", "9000"]
