version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    ports:
        - "8000:8000"  # Mapeia a porta 8000 do host para a porta 8000 do container
    volumes:
      - ./:/var/www
    networks:
      - laravelnet



networks:
  laravelnet:
    driver: bridge
