name: Deploy via FTP
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Test FTP Connection
        run: |
          sudo apt-get update
          sudo apt-get install -y ftp
          ftp -inv ${{ secrets.ftp_host }} << EOF
          user ${{ secrets.ftp_user }} ${{ secrets.ftp_password }}
          bye
          EOF

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.ftp_host }}
          user: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          localDir: "dist"
          remoteDir: "public_html"
