name: Deploy via ftp
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Adiciona uma etapa para instalar as dependências necessárias (se houver)
      - name: Install Dependencies
        run: npm install

      # Adiciona uma etapa para construir seu projeto e criar o diretório 'dist'
      - name: Build Project
        run: npm run build

      # Adiciona uma etapa para listar os arquivos (opcional, para debug)
      - name: List files in the workspace
        run: ls -la 

      # Etapa para fazer o deploy via FTP
      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.ftp_host }}
          user: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          localDir: "dist"
          remoteDir: "public_html"
