name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: List files in the workspace
        run: ls -la dist

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.ftp_host }}
          user: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          localDir: "dist"
          remoteDir: "public_html"
